# Generated by Django 3.0.7 on 2020-07-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellom',
            name='cellid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enbom',
            name='enb',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
