# Generated by Django 3.0.7 on 2020-07-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omquery', '0004_nimstmus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nimstmus',
            name='Cell_Radius',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nimstmus',
            name='antenna_height_ft',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nimstmus',
            name='latitude_sector',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nimstmus',
            name='longitude_sector',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nimstmus',
            name='mechanical_tilt',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True),
        ),
    ]
